// Popüler BIST hisseleri — yerel arama listesi.
// Arama bu liste üzerinden yapılır (sembol veya ada göre), fiyat Yahoo'dan gelir.
// Yeni hisse eklemek = buraya bir satır eklemek.

export interface BistStock {
  symbol: string;
  name: string;
}

export const BIST: BistStock[] = [
  { symbol: 'THYAO', name: 'Türk Hava Yolları' },
  { symbol: 'ASELS', name: 'Aselsan' },
  { symbol: 'GARAN', name: 'Garanti BBVA' },
  { symbol: 'AKBNK', name: 'Akbank' },
  { symbol: 'ISCTR', name: 'İş Bankası (C)' },
  { symbol: 'YKBNK', name: 'Yapı Kredi Bankası' },
  { symbol: 'VAKBN', name: 'VakıfBank' },
  { symbol: 'HALKB', name: 'Halkbank' },
  { symbol: 'EREGL', name: 'Ereğli Demir Çelik' },
  { symbol: 'ISDMR', name: 'İskenderun Demir Çelik' },
  { symbol: 'KRDMD', name: 'Kardemir (D)' },
  { symbol: 'KCHOL', name: 'Koç Holding' },
  { symbol: 'SAHOL', name: 'Sabancı Holding' },
  { symbol: 'SISE', name: 'Şişecam' },
  { symbol: 'TUPRS', name: 'Tüpraş' },
  { symbol: 'PETKM', name: 'Petkim' },
  { symbol: 'BIMAS', name: 'BİM Mağazalar' },
  { symbol: 'MGROS', name: 'Migros' },
  { symbol: 'SOKM', name: 'Şok Marketler' },
  { symbol: 'BIZIM', name: 'Bizim Toptan' },
  { symbol: 'FROTO', name: 'Ford Otosan' },
  { symbol: 'TOASO', name: 'Tofaş Oto' },
  { symbol: 'DOAS', name: 'Doğuş Otomotiv' },
  { symbol: 'OTKAR', name: 'Otokar' },
  { symbol: 'KARSN', name: 'Karsan' },
  { symbol: 'TTRAK', name: 'Türk Traktör' },
  { symbol: 'ARCLK', name: 'Arçelik' },
  { symbol: 'VESTL', name: 'Vestel' },
  { symbol: 'PGSUS', name: 'Pegasus' },
  { symbol: 'TAVHL', name: 'TAV Havalimanları' },
  { symbol: 'TCELL', name: 'Turkcell' },
  { symbol: 'TTKOM', name: 'Türk Telekom' },
  { symbol: 'SASA', name: 'Sasa Polyester' },
  { symbol: 'HEKTS', name: 'Hektaş' },
  { symbol: 'GUBRF', name: 'Gübre Fabrikaları' },
  { symbol: 'KOZAL', name: 'Koza Altın' },
  { symbol: 'KOZAA', name: 'Koza Anadolu' },
  { symbol: 'IPEKE', name: 'İpek Doğal Enerji' },
  { symbol: 'ENKAI', name: 'Enka İnşaat' },
  { symbol: 'TKFEN', name: 'Tekfen Holding' },
  { symbol: 'ALARK', name: 'Alarko Holding' },
  { symbol: 'DOHOL', name: 'Doğan Holding' },
  { symbol: 'ECILC', name: 'Eczacıbaşı İlaç' },
  { symbol: 'SELEC', name: 'Selçuk Ecza Deposu' },
  { symbol: 'EKGYO', name: 'Emlak Konut GYO' },
  { symbol: 'ENJSA', name: 'Enerjisa Enerji' },
  { symbol: 'AKSEN', name: 'Aksa Enerji' },
  { symbol: 'ZOREN', name: 'Zorlu Enerji' },
  { symbol: 'ODAS', name: 'Odaş Elektrik' },
  { symbol: 'GWIND', name: 'Galata Wind Enerji' },
  { symbol: 'ASTOR', name: 'Astor Enerji' },
  { symbol: 'SMRTG', name: 'Smart Güneş' },
  { symbol: 'KONTR', name: 'Kontrolmatik' },
  { symbol: 'GESAN', name: 'Girişim Elektrik' },
  { symbol: 'EUPWR', name: 'Europower Enerji' },
  { symbol: 'CIMSA', name: 'Çimsa' },
  { symbol: 'OYAKC', name: 'Oyak Çimento' },
  { symbol: 'BUCIM', name: 'Bursa Çimento' },
  { symbol: 'NUHCM', name: 'Nuh Çimento' },
  { symbol: 'KONYA', name: 'Konya Çimento' },
  { symbol: 'CCOLA', name: 'Coca-Cola İçecek' },
  { symbol: 'AEFES', name: 'Anadolu Efes' },
  { symbol: 'ULKER', name: 'Ülker Bisküvi' },
  { symbol: 'BANVT', name: 'Banvit' },
  { symbol: 'MAVI', name: 'Mavi Giyim' },
  { symbol: 'LOGO', name: 'Logo Yazılım' },
  { symbol: 'REEDR', name: 'Reeder Teknoloji' },
  { symbol: 'QUAGR', name: 'Qua Granite' },
  { symbol: 'BRSAN', name: 'Borusan Boru' },
  { symbol: 'BRYAT', name: 'Borusan Yatırım' },
  { symbol: 'AKSA', name: 'Aksa Akrilik' },
  { symbol: 'ALFAS', name: 'Alfa Solar Enerji' },
  { symbol: 'TABGD', name: 'TAB Gıda' },
  { symbol: 'MPARK', name: 'MLP Sağlık (Medical Park)' },
  { symbol: 'AGHOL', name: 'AG Anadolu Grubu Holding' },
];
